### ISSUE TITLE
Change of displayed file order fails api 2.0 workflow test

### ISSUE THREAD

**Issue by iceiilin** [RackHD/on-http#229] opened 2016-04-15 05:58 UTC
Change findEntries() in lib/service/files/file-plugin.js to return files in time-desc order fails API 2.0 test_node_workflows_post Jenkins test, while the modified file isn't injected in API 2.0 related files. Detailed error message can be found from https://github.com/RackHD/on-http/pull/222

**Comment by abildw** [comment] 2016-04-29 14:24
duplicate of 
https://github.com/RackHD/RackHD/issues/172

**Comment by brianparry** [comment] 2016-04-29 14:26
Closing as a duplicate

**Closed by brianparry** 2016-04-29 14:26 UTC
Labels: duplicate, enhancement
